### ISSUE TITLE
nginx的配置

### ISSUE THREAD

**Issue by yjdjiayou** [Vitaminaq/Confession-Wall#1]
可以看下你的nginx的配置吗

**Comment by Vitaminaq** [comment]
不好意思，这个项目都差不多废弃了，所以平时没怎么逛，nginx只是简单的做了一层接口转发，我们访问的是服务器80端口，而接口跑着3000，所以需要配置个正则，location /api/什么的 {
        proxy_pass  http://apachephp:3000; 
    }
等之类的。

**Comment by Vitaminaq** [comment]
server下的结点：

listen：监听80端口

server_name：转发到哪个地址

proxy_pass：代理到哪个地址
